version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.0.1


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/python:3.10.4
    working_directory: ~/project
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linting
          command: flake8

  build-and-push:
    docker:
      - image: docker
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker build -t opc-p13-lettings:latest .
          docker tag opc-p13-lettings tristanmn/opc-p13-lettings:latest
          docker push tristanmn/opc-p13-lettings:latest
  
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Storing previous commit
          command: |
            git rev-parse HEAD > ./commit.txt
      - heroku/install
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Pushing to heroku registry
          command: |
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: main
  build-and-push-and-deploy:
    jobs:
      - build-and-test:
          context: public
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
          context: public
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main
          context: public
